import assert from 'node:assert/strict';
import {PALETTE, configureSelectionPalette, getSelectionPalette, normalizePaletteColors, palettePickerHex, resolvePalette, AnnotationStore} from '../src/annotations';
import {MemoryAdapter} from './memory-adapter';
const defaults=JSON.stringify(PALETTE);
assert.deepEqual(normalizePaletteColors(null),['','','','']);
assert.deepEqual(normalizePaletteColors(['#12abEf','red','url(javascript:x)','#ABCDEF','#111111']),['#12ABEF','','','#ABCDEF']);
configureSelectionPalette(['#00ff00','#000000','#FFFFFF','#123456']);
assert.deepEqual(getSelectionPalette().map(p=>p.fill),['#00FF00','#000000','#FFFFFF','#123456']);
assert.equal(JSON.stringify(PALETTE),defaults,'preferences must not change historical color interpretation');
assert.equal(resolvePalette('rgba(106, 217, 126, 0.42)')?.name,'blue');
assert.equal(resolvePalette(PALETTE[0].fill)?.fill,PALETTE[0].fill);
assert.equal(palettePickerHex(PALETTE[1]),'#489eff');
const saved=JSON.parse(JSON.stringify(normalizePaletteColors(['#123456'])));
configureSelectionPalette(saved);
assert.equal(getSelectionPalette()[0].fill,'#123456');
assert.equal(getSelectionPalette()[1].fill,PALETTE[1].fill);
configureSelectionPalette([]);
assert.deepEqual(getSelectionPalette(),PALETTE,'reset restores exact original fill/alpha/ink');
console.log('palette smoke: validation, four slots, persistence, reset, and unchanged historical colors passed');
